#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Che-Theia workflow
# matrix jobs with alpine and ubi8
name: CI

# Trigger the workflow on push or pull request
on: 
  push:
    branches: buildx-GA
  

jobs:
  # check EOF newline
  linelint:
    runs-on: ubuntu-20.04
    name: eof-newline
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linelint
        uses: fernandrone/linelint@0.0.5
        id: linelint
     
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
  node-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout che-theia source code
    - uses: actions/setup-node@v1
      name: Configuring nodejs 10.x version
      with:
        node-version: '12.x'
        
    - name: build
      run: yarn
  image-build:
    strategy:
      matrix:
        dist: [ 'alpine', 'ubi8' ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout che-theia source code
    - uses: actions/setup-node@v1
      name: Configuring nodejs 10.x version
      with:
        node-version: '12.x'
    - name: build
      run: |
        export buildx=1
        #docker image prune -a -f
        #docker pull quay.io/eclipse/che-theia-dev:next
        #docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
        ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.${{matrix.dist}}
